global using FluentValidation;
global using Givt.Backend.Bff.Retool.Service;
global using Givt.Backend.Bff.Retool.Service.Configurations;
global using Givt.Backend.Bff.Retool.Service.Controllers.Notification.v1;
global using Givt.Backend.Bff.Retool.Service.Controllers.Notification.v1.Models;
global using Givt.Backend.Bff.Retool.Service.Controllers.Notification.v1.Requests.v1;
global using Microsoft.AspNetCore.Mvc;
global using Microsoft.OpenApi.Models;
global using System.Reflection;
global using Model = Givt.Backend.Bff.Retool.Service.Controllers.Notification.v1.Models;
