global using FluentValidation;
global using Givt.Backend.Bff.Retool.Service;
global using Givt.Backend.Bff.Retool.Service.Configurations;
global using Givt.Backend.Bff.Retool.Service.Controllers.Notification.v1;
global using Givt.Backend.Bff.Retool.Service.Controllers.Notification.v1.Requests.v1;
global using Givt.Backend.Core.Notification.Contracts.Notification.v1;
global using Givt.Common.Library.ConfigurationExtensions;
global using Mapster;
global using Microsoft.AspNetCore.Mvc;
global using Microsoft.Extensions.Options;
global using Microsoft.OpenApi.Models;
global using System.Reflection;
global using BffModels = Givt.Backend.Bff.Retool.Service.Controllers.Notification.v1.Models;
global using CoreModels = Givt.Backend.Core.Notification.Contracts.Notification.v1.Models;
