apiVersion: v1
kind: Service
metadata:
  name: givt-backend-bff-retool-service

spec:
  ports:
    - name: web
      port: 80
      protocol: TCP
      targetPort: web 

  selector:
    app: givt-backend-bff-retool-service 